<?php 
return [
    'created_at'         => 1561714288,
    'meta'               => [
        'name'         => 'Reseller Package',
        'version'      => '1.0',
        'author'       => 'Tahmied Hossain',
        'opening-type' => 'normal',
    ],
    'show_on_adminArea'  => true,
    'show_on_clientArea' => true,
    'status'             => true,
    'access_ps'          => [],
    'settings'           => [
        'category_slug'      => 'reseller-hosting',
        'badge_label'        => 'Reseller Exclusive',
        'pricing_table_html' => '<div> fuck it </div>',
        'product_ids'        => '104',
        'page_path'          => '/category/hosting/',
        'page_slug'          => 'reseller-hosting',
        'add_to_cart_label'  => 'Add to Cart',
        'page_1_page_path'   => '/category/hosting/',
        'page_1_page_slug'   => 'reseller-hosting',
        'page_1_product_ids' => '104,36',
        'page_2_page_path'   => '/category/hosting/',
        'page_2_page_slug'   => 'professional-ssd-hosting',
        'page_2_product_ids' => '36',
        'page_3_page_path'   => '',
        'page_3_page_slug'   => '',
        'page_3_product_ids' => '',
        'page_4_page_path'   => '',
        'page_4_page_slug'   => '',
        'page_4_product_ids' => '',
        'page_5_page_path'   => '',
        'page_5_page_slug'   => '',
        'page_5_product_ids' => '',
    ],
];
